### ISSUE TITLE
Please publish a package on pypi

### ISSUE THREAD

**Issue by callebtc** [lc6chang/ecc-pycrypto#20]
I'm using your (awesome) library and I'd like to include it in a project. It would be so much easier if I could just pip install it. 

Thank you!

**Comment by lc6chang** [comment]
Sorry for the late reply. I will think about it. But my concern is that I need a better package name. There are already many packages similar to `ecc` on pypi now. Actually `pip` can work with GitHub VCS url, for example:
```bash
pip install git+ssh://git@github.com/lc6chang/ecc-pycrypto.git@master
# or
pip install https://github.com/lc6chang/ecc-pycrypto/archive/master.zip 
```
It can also be included in `setup.py` in the same way. Does it work for you?
